version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - mysql-compose-network
    depends_on:
      - mysqlsrv

  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "teste123"
      MYSQL_DATABASE: "desafio-dev"
    ports:
      - "3307:3306"
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge